---
#- name: add mongo key
#  apt_key: state=present id=ACCC4CF8 url=https://www.postgresql.org/media/keys/ACCC4CF8.asc
#- name: add postgres repository
#  apt_repository: state=present update_cache=yes repo="deb http://downloads-distro.mongodb.org/repo/ubuntu-upstart dist 10gen"
- name: install mongodb
  apt: pkg=mongodb update_cache=yes
- name: open mongodb port 27017
  lineinfile: dest=/etc/mongodb.conf regexp="^bind_ip = 127.0.0.1$" line="bind_ip = 0.0.0.0"
  notify:
    - restart mongodb
