---
- name: load extensions
  command: psql {{dbname}} -c "CREATE EXTENSION {{item}}"
  sudo_user: postgres
  with_items: extensions
- name: restart postgres
  service: name=postgresql state=restarted
